### ISSUE TITLE
Haven't been able to make zotero picker work

### ISSUE THREAD

**Issue by ccamara** [oztalha/zotero-picker#1]
Working with zotero like I do in Libreoffice is what was preventing me from using markdown to write and publish my academic papers, so I got very excited when I found this atom plugin! However, after having installed it I haven't been able to make it work, not haven't been able to find any documentation in order to use it.

That's what I've done so far:

1. Installed zotero picker from atom's preferences.
1. Restarted atom
1. Installed [Better Bibtex](https://github.com/retorquere/zotero-better-bibtex) as requested, which automatically generates Citation Key per each item.
1. Kept Firefox open (I am using Zotero as a Firefox plugin)
1. Created a markdown file

Unfortunately nothing happens when I Pressed alt+z (as well as used menu item and command palette). Am I missing something?

**Comment by oztalha** [comment]
What happens when you go to http://localhost:23119/better-bibtex/cayw on your browser? Picker supposed to pop up. Alternatively, try this: https://github.com/retorquere/zotero-citations ; now doing the same job as zotero-picker.

**Comment by ccamara** [comment]
> What happens when you go to http://localhost:23119/better-bibtex/cayw on your browser?

Nothing: page not found. But that's not a surprise since I just installed Better Bibtex as a Firefox XPI extension, like explained [here](https://github.com/retorquere/zotero-better-bibtex/wiki/Installation)

**Comment by ccamara** [comment]
Since Better Bibtex instructions specifically mention zotero standalone I tried using it instead of Firefox's extension and now the picker does show up and inserts references in the shape `@key` (not `[@key]` -there are no brackets). I didn't find any documentation to generate bibliography or how to convert those references into citations.

**Comment by oztalha** [comment]
Good to hear that it works for you now. Actually, this is what it only does, please see the (updated) `WHAT` and `HOW` sections of the [ReadMe](https://github.com/oztalha/zotero-picker/blob/master/README.md).

**Comment by ccamara** [comment]
Thank you for the more detailed instructions! I have never used pandoc yet, but I haven't seen anywhere how are we to control where the bibliography is placed within the document.

**Comment by oztalha** [comment]
Pandoc appends the bibliography to the end of the output file. So you can finish your markdown (input) file with the title `#References` or `#Bibliography`. And when you run the `pandoc` command, you'll see the bibliography appended to your output file. 

Btw, you can set the citation style as well, by default Pandoc uses `Chicago` style, but you can download and use [some other style](https://www.zotero.org/styles) too (e.g. just add this parameter to your pandoc command `--csl=mystyle.csl`).
